name: Build Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: quantumwake/alethic-ism-github-actions@main
        with:
          image-name: 'krasaee/alethic-ism-state-online-join'
          registry-username: ${{ vars.DOCKERHUB_USERNAME }}
          registry-token: ${{ secrets.DOCKERHUB_TOKEN }}
          should-deploy: 'false'