name: Build Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: quantumwake/alethic-ism-github-actions@main
        with:
          image-name: 'krasaee/alethic-ism-state-online-join'
          registry-username: ${{ vars.DOCKERHUB_USERNAME }}
          registry-token: ${{ secrets.DOCKERHUB_TOKEN }}
          should-deploy: 'true'
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          k8s-config: 'doctl kubernetes cluster kubeconfig save --expiry-seconds 600 qwake-k8s-cluster'
          k8s-namespace: 'alethic'
          k8s-deployment: 'alethic-ism-state-online-join-deployment'
          deployment-file: 'k8s/deployment.yaml'
          create-github-release: 'true'